apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyspot6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyspot6
  template:
    metadata:
      labels:
        app: moneyspot6
    spec:
      containers:
      - image: dvetter/moneyspot6
        name: moneyspot6
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ConnectionStrings__Db
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: ConnectionString
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://192.168.178.111:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_SERVICE_NAME
          value: MoneySpot6.WebApp
---
apiVersion: v1
kind: Service
metadata:
  name: moneyspot6-web-app-service
spec:
  selector:
    app: moneyspot6
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moneyspot6-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: money.dvetter.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moneyspot6-web-app-service
                port:
                  number: 80
                  