apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyspot6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyspot6
  template:
    metadata:
      labels:
        app: moneyspot6
    spec:
      containers:
      - image: dvetter/moneyspot6
        name: moneyspot6
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ConnectionStrings__Db
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: ConnectionString