//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({providedIn: 'root'})
export class TransactionPageClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getTransactions(search: string | null | undefined): Observable<TransactionResponse> {
        let url_ = this.baseUrl + "/api/TransactionPage?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTransactions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTransactions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TransactionResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TransactionResponse>;
        }));
    }

    protected processGetTransactions(response: HttpResponseBase): Observable<TransactionResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TransactionResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({providedIn: 'root'})
export class SummaryPageClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getBankAccountSummary(): Observable<BankAccountSummaryResponse> {
        let url_ = this.baseUrl + "/api/SummaryPage/GetBankAccountSummary";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetBankAccountSummary(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetBankAccountSummary(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BankAccountSummaryResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BankAccountSummaryResponse>;
        }));
    }

    protected processGetBankAccountSummary(response: HttpResponseBase): Observable<BankAccountSummaryResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BankAccountSummaryResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getBankAccountGoal(): Observable<BankAccountTotalGoalResponse> {
        let url_ = this.baseUrl + "/api/SummaryPage/GetBankAccountGoal";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetBankAccountGoal(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetBankAccountGoal(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BankAccountTotalGoalResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BankAccountTotalGoalResponse>;
        }));
    }

    protected processGetBankAccountGoal(response: HttpResponseBase): Observable<BankAccountTotalGoalResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BankAccountTotalGoalResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({providedIn: 'root'})
export class StockChartPageClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getStocks(): Observable<StockResponse[]> {
        let url_ = this.baseUrl + "/api/StockChartPage/GetStocks";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetStocks(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetStocks(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StockResponse[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StockResponse[]>;
        }));
    }

    protected processGetStocks(response: HttpResponseBase): Observable<StockResponse[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(StockResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getHistory(stockId: number | undefined, start: Date | null | undefined, end: Date | null | undefined, interval: StockPriceInterval | undefined): Observable<StockPriceResponse[]> {
        let url_ = this.baseUrl + "/api/StockChartPage/GetHistory?";
        if (stockId === null)
            throw new Error("The parameter 'stockId' cannot be null.");
        else if (stockId !== undefined)
            url_ += "stockId=" + encodeURIComponent("" + stockId) + "&";
        if (start !== undefined && start !== null)
            url_ += "start=" + encodeURIComponent(start ? "" + start.toISOString() : "") + "&";
        if (end !== undefined && end !== null)
            url_ += "end=" + encodeURIComponent(end ? "" + end.toISOString() : "") + "&";
        if (interval === null)
            throw new Error("The parameter 'interval' cannot be null.");
        else if (interval !== undefined)
            url_ += "interval=" + encodeURIComponent("" + interval) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetHistory(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetHistory(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StockPriceResponse[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StockPriceResponse[]>;
        }));
    }

    protected processGetHistory(response: HttpResponseBase): Observable<StockPriceResponse[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(StockPriceResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({providedIn: 'root'})
export class IncomeExpenseClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    get(search: string | null | undefined, grouping: IncomeExpenseGrouping): Observable<IncomeExpenseEntryResponse[]> {
        let url_ = this.baseUrl + "/api/IncomeExpense/GetMonthlyIncomeAndExpenses?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (grouping === undefined || grouping === null)
            throw new Error("The parameter 'grouping' must be defined and cannot be null.");
        else
            url_ += "grouping=" + encodeURIComponent("" + grouping) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGet(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGet(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<IncomeExpenseEntryResponse[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<IncomeExpenseEntryResponse[]>;
        }));
    }

    protected processGet(response: HttpResponseBase): Observable<IncomeExpenseEntryResponse[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(IncomeExpenseEntryResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({providedIn: 'root'})
export class AccountHistoryClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    get(accountIds: number[], startDate: string, endDate: string): Observable<AccountHistoryBalanceResponse[]> {
        let url_ = this.baseUrl + "/api/AccountHistory?";
        if (accountIds === undefined || accountIds === null)
            throw new Error("The parameter 'accountIds' must be defined and cannot be null.");
        else
            accountIds && accountIds.forEach(item => { url_ += "accountIds=" + encodeURIComponent("" + item) + "&"; });
        if (startDate === undefined || startDate === null)
            throw new Error("The parameter 'startDate' must be defined and cannot be null.");
        else
            url_ += "startDate=" + encodeURIComponent("" + startDate) + "&";
        if (endDate === undefined || endDate === null)
            throw new Error("The parameter 'endDate' must be defined and cannot be null.");
        else
            url_ += "endDate=" + encodeURIComponent("" + endDate) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGet(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGet(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AccountHistoryBalanceResponse[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AccountHistoryBalanceResponse[]>;
        }));
    }

    protected processGet(response: HttpResponseBase): Observable<AccountHistoryBalanceResponse[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(AccountHistoryBalanceResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({providedIn: 'root'})
export class DebugClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    reprocessTransactionParsing(): Observable<void> {
        let url_ = this.baseUrl + "/api/Debug/ReprocessTransactionParsing";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReprocessTransactionParsing(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReprocessTransactionParsing(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processReprocessTransactionParsing(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    reimportLast30DayStocks(): Observable<void> {
        let url_ = this.baseUrl + "/api/Debug/ReimportLast30DayStocks";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReimportLast30DayStocks(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReimportLast30DayStocks(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processReimportLast30DayStocks(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getRunningAdapters(): Observable<RunningProcessResponse[]> {
        let url_ = this.baseUrl + "/api/Debug/GetRunningAdapters";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRunningAdapters(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRunningAdapters(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RunningProcessResponse[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RunningProcessResponse[]>;
        }));
    }

    protected processGetRunningAdapters(response: HttpResponseBase): Observable<RunningProcessResponse[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RunningProcessResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class TransactionResponse implements ITransactionResponse {
    entries?: TransactionEntryResponse[];

    constructor(data?: ITransactionResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["entries"])) {
                this.entries = [] as any;
                for (let item of _data["entries"])
                    this.entries!.push(TransactionEntryResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TransactionResponse {
        data = typeof data === 'object' ? data : {};
        let result = new TransactionResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.entries)) {
            data["entries"] = [];
            for (let item of this.entries)
                data["entries"].push(item.toJSON());
        }
        return data;
    }
}

export interface ITransactionResponse {
    entries?: TransactionEntryResponse[];
}

export class TransactionEntryResponse implements ITransactionEntryResponse {
    id?: number;
    icon?: string | undefined;
    iconColor?: string | undefined;
    date?: Date;
    name?: string | undefined;
    purpose?: string | undefined;
    value?: number;

    constructor(data?: ITransactionEntryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.icon = _data["icon"];
            this.iconColor = _data["iconColor"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.name = _data["name"];
            this.purpose = _data["purpose"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): TransactionEntryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new TransactionEntryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["icon"] = this.icon;
        data["iconColor"] = this.iconColor;
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["name"] = this.name;
        data["purpose"] = this.purpose;
        data["value"] = this.value;
        return data;
    }
}

export interface ITransactionEntryResponse {
    id?: number;
    icon?: string | undefined;
    iconColor?: string | undefined;
    date?: Date;
    name?: string | undefined;
    purpose?: string | undefined;
    value?: number;
}

export class BankAccountSummaryResponse implements IBankAccountSummaryResponse {
    accounts!: BankAccountEntrySummaryResponse[];
    total!: number;

    constructor(data?: IBankAccountSummaryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.accounts = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["accounts"])) {
                this.accounts = [] as any;
                for (let item of _data["accounts"])
                    this.accounts!.push(BankAccountEntrySummaryResponse.fromJS(item));
            }
            this.total = _data["total"];
        }
    }

    static fromJS(data: any): BankAccountSummaryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BankAccountSummaryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.accounts)) {
            data["accounts"] = [];
            for (let item of this.accounts)
                data["accounts"].push(item.toJSON());
        }
        data["total"] = this.total;
        return data;
    }
}

export interface IBankAccountSummaryResponse {
    accounts: BankAccountEntrySummaryResponse[];
    total: number;
}

export class BankAccountEntrySummaryResponse implements IBankAccountEntrySummaryResponse {
    id?: number;
    name?: string;
    total?: number;

    constructor(data?: IBankAccountEntrySummaryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.total = _data["total"];
        }
    }

    static fromJS(data: any): BankAccountEntrySummaryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BankAccountEntrySummaryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["total"] = this.total;
        return data;
    }
}

export interface IBankAccountEntrySummaryResponse {
    id?: number;
    name?: string;
    total?: number;
}

export class BankAccountTotalGoalResponse implements IBankAccountTotalGoalResponse {
    endDate!: Date;
    endBalance!: number;
    requiredSavingPerMonth!: number;
    actualHistory!: BalanceEntryResponse[];
    expectedHistory!: BalanceEntryResponse[];

    constructor(data?: IBankAccountTotalGoalResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.actualHistory = [];
            this.expectedHistory = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.endBalance = _data["endBalance"];
            this.requiredSavingPerMonth = _data["requiredSavingPerMonth"];
            if (Array.isArray(_data["actualHistory"])) {
                this.actualHistory = [] as any;
                for (let item of _data["actualHistory"])
                    this.actualHistory!.push(BalanceEntryResponse.fromJS(item));
            }
            if (Array.isArray(_data["expectedHistory"])) {
                this.expectedHistory = [] as any;
                for (let item of _data["expectedHistory"])
                    this.expectedHistory!.push(BalanceEntryResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BankAccountTotalGoalResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BankAccountTotalGoalResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["endDate"] = this.endDate ? formatDate(this.endDate) : <any>undefined;
        data["endBalance"] = this.endBalance;
        data["requiredSavingPerMonth"] = this.requiredSavingPerMonth;
        if (Array.isArray(this.actualHistory)) {
            data["actualHistory"] = [];
            for (let item of this.actualHistory)
                data["actualHistory"].push(item.toJSON());
        }
        if (Array.isArray(this.expectedHistory)) {
            data["expectedHistory"] = [];
            for (let item of this.expectedHistory)
                data["expectedHistory"].push(item.toJSON());
        }
        return data;
    }
}

export interface IBankAccountTotalGoalResponse {
    endDate: Date;
    endBalance: number;
    requiredSavingPerMonth: number;
    actualHistory: BalanceEntryResponse[];
    expectedHistory: BalanceEntryResponse[];
}

export class BalanceEntryResponse implements IBalanceEntryResponse {
    date!: Date;
    balance!: number;

    constructor(data?: IBalanceEntryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.balance = _data["balance"];
        }
    }

    static fromJS(data: any): BalanceEntryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BalanceEntryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["balance"] = this.balance;
        return data;
    }
}

export interface IBalanceEntryResponse {
    date: Date;
    balance: number;
}

export class StockResponse implements IStockResponse {
    id?: number;
    name?: string;

    constructor(data?: IStockResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): StockResponse {
        data = typeof data === 'object' ? data : {};
        let result = new StockResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IStockResponse {
    id?: number;
    name?: string;
}

export class StockPriceResponse implements IStockPriceResponse {
    timestamp!: Date;
    open!: number;
    close!: number;
    high!: number;
    low!: number;
    volume!: number;

    constructor(data?: IStockPriceResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timestamp = _data["timestamp"] ? new Date(_data["timestamp"].toString()) : <any>undefined;
            this.open = _data["open"];
            this.close = _data["close"];
            this.high = _data["high"];
            this.low = _data["low"];
            this.volume = _data["volume"];
        }
    }

    static fromJS(data: any): StockPriceResponse {
        data = typeof data === 'object' ? data : {};
        let result = new StockPriceResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timestamp"] = this.timestamp ? this.timestamp.toISOString() : <any>undefined;
        data["open"] = this.open;
        data["close"] = this.close;
        data["high"] = this.high;
        data["low"] = this.low;
        data["volume"] = this.volume;
        return data;
    }
}

export interface IStockPriceResponse {
    timestamp: Date;
    open: number;
    close: number;
    high: number;
    low: number;
    volume: number;
}

export enum StockPriceInterval {
    FiveMinutes = 5,
    Daily = 1440,
}

export class IncomeExpenseEntryResponse implements IIncomeExpenseEntryResponse {
    year?: number | undefined;
    month?: number | undefined;
    income!: number;
    expense!: number;

    constructor(data?: IIncomeExpenseEntryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.year = _data["year"];
            this.month = _data["month"];
            this.income = _data["income"];
            this.expense = _data["expense"];
        }
    }

    static fromJS(data: any): IncomeExpenseEntryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new IncomeExpenseEntryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["year"] = this.year;
        data["month"] = this.month;
        data["income"] = this.income;
        data["expense"] = this.expense;
        return data;
    }
}

export interface IIncomeExpenseEntryResponse {
    year?: number | undefined;
    month?: number | undefined;
    income: number;
    expense: number;
}

export enum IncomeExpenseGrouping {
    None = 0,
    Month = 1,
    Year = 2,
}

export class AccountHistoryBalanceResponse implements IAccountHistoryBalanceResponse {
    date!: Date;
    balance!: number;

    constructor(data?: IAccountHistoryBalanceResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.balance = _data["balance"];
        }
    }

    static fromJS(data: any): AccountHistoryBalanceResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AccountHistoryBalanceResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["balance"] = this.balance;
        return data;
    }
}

export interface IAccountHistoryBalanceResponse {
    date: Date;
    balance: number;
}

export class RunningProcessResponse implements IRunningProcessResponse {
    processId?: number;
    startTime?: Date | undefined;
    error?: string | undefined;

    constructor(data?: IRunningProcessResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.processId = _data["processId"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.error = _data["error"];
        }
    }

    static fromJS(data: any): RunningProcessResponse {
        data = typeof data === 'object' ? data : {};
        let result = new RunningProcessResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["processId"] = this.processId;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["error"] = this.error;
        return data;
    }
}

export interface IRunningProcessResponse {
    processId?: number;
    startTime?: Date | undefined;
    error?: string | undefined;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}