variables:
  NAME: "moneyspot"
  HOST_PROD: 192.168.178.200
  HOST_STAGING: 192.168.178.201

stages:
  - build
  - release-staging

build:
  stage: build
  script:
    - docker build . -t docker.dvetter.net/$NAME/$NAME -t docker.dvetter.net/$NAME/$NAME:latest -t docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA
    - docker push docker.dvetter.net/$NAME/$NAME
    - docker push docker.dvetter.net/$NAME/$NAME:latest
    - docker push docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA

release-staging:
  stage: release-staging  
  only:
    - develop
  script:
    - export DOCKER_HOST=ssh://root@$HOST_STAGING
    - docker stop $NAME || true
    - docker rm $NAME || true
    - docker pull docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA
    - >
      docker run -d --restart always -p 80:80 --name $NAME 
      -e ASPNETCORE_ENVIRONMENT="Staging"
      -e OTEL_EXPORTER_OTLP_ENDPOINT="http://192.168.178.111:4318"
      -e OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      -e OTEL_SERVICE_NAME="$NAME-app-staging"
      -e ConnectionStrings__Db="User ID=postgres;Password=$DB_PASSWORD;Host=192.168.178.105;Port=5432;Database=$NAME-db-staging;ApplicationName=$NAME-staging"
      docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA
    - docker image prune -af

release-prod:
  stage: release-staging  
  only:
    - master
  script:
    - export DOCKER_HOST=ssh://root@$HOST_PROD
    - docker stop $NAME || true
    - docker rm $NAME || true
    - docker pull docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA
    - >
      docker run -d --restart always -p 80:80 --name $NAME 
      -e ASPNETCORE_ENVIRONMENT="Production"
      -e OTEL_EXPORTER_OTLP_ENDPOINT="http://192.168.178.111:4318"
      -e OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      -e OTEL_SERVICE_NAME="$NAME-app-prod"
      -e ConnectionStrings__Db="User ID=postgres;Password=$DB_PASSWORD;Host=192.168.178.105;Port=5432;Database=$NAME-db-prod;ApplicationName=$NAME-prod"
      docker.dvetter.net/$NAME/$NAME:$CI_COMMIT_SHA
    - docker image prune -af