// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneySpot6.WebApp.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneySpot6.WebApp.Database.Migrations.PostgresMigrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20251003040354_Added sort keys to rules")]
    partial class Addedsortkeystorules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BankConnectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("IconColor")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name2")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("Final", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Final#DbBankAccountTransactionFinalData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AlternateInitiator")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AlternateReceiver")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("CreditorIdentifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("EndToEndReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MandateReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OriginatorIdentifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PaymentProcessor")
                                .HasColumnType("integer");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Overridden", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Overridden#DbBankAccountTransactionOverrideData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("text");

                            b1.Property<string>("AlternateInitiator")
                                .HasColumnType("text");

                            b1.Property<string>("AlternateReceiver")
                                .HasColumnType("text");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("BankCode")
                                .HasColumnType("text");

                            b1.Property<string>("Bic")
                                .HasColumnType("text");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("CreditorIdentifier")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("EndToEndReference")
                                .HasColumnType("text");

                            b1.Property<string>("Iban")
                                .HasColumnType("text");

                            b1.Property<string>("MandateReference")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("OriginatorIdentifier")
                                .HasColumnType("text");

                            b1.Property<int?>("PaymentProcessor")
                                .HasColumnType("integer");

                            b1.Property<string>("Purpose")
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Parsed", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Parsed#DbBankAccountTransactionParsedData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AlternateInitiator")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AlternateReceiver")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("CreditorIdentifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("EndToEndReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MandateReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OriginatorIdentifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PaymentProcessor")
                                .HasColumnType("integer");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Raw", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Raw#DbBankAccountTransactionRawData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddKey")
                                .HasColumnType("text");

                            b1.Property<string>("Additional")
                                .HasColumnType("text");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("ChargeAmount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("text");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("EndToEndId")
                                .HasColumnType("text");

                            b1.Property<string>("InstituteReference")
                                .HasColumnType("text");

                            b1.Property<bool>("IsCamt")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsCancelation")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsSepa")
                                .HasColumnType("boolean");

                            b1.Property<string>("MandateId")
                                .HasColumnType("text");

                            b1.Property<decimal>("NewBalance")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("OriginalAmount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Primanota")
                                .HasColumnType("text");

                            b1.Property<string>("Purpose")
                                .HasColumnType("text");

                            b1.Property<string>("PurposeCode")
                                .HasColumnType("text");

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.ComplexProperty<Dictionary<string, object>>("Counterparty", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Raw#DbBankAccountTransactionRawData.Counterparty#CounterpartyAccount", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("BankCode")
                                        .HasColumnType("text");

                                    b2.Property<string>("Bic")
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .HasColumnType("text");

                                    b2.Property<string>("Iban")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name2")
                                        .HasColumnType("text");

                                    b2.Property<string>("Number")
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankAccountTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HbciVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSuccessfulSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Passport")
                        .HasColumnType("bytea");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoAssignmentCounterpartyRegex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutoAssignmentPurposeRegex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("LastImport5Min")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastImportDaily")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastImportError5Min")
                        .HasColumnType("text");

                    b.Property<string>("LastImportErrorDaily")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockPrices");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankConnection", "BankConnection")
                        .WithMany()
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbCategory", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockPrice", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbStock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbStock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
