// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneySpot6.WebApp.Database;

#nullable disable

namespace MoneySpot6.WebApp.Database.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260415001521_Added update log table")]
    partial class Addedupdatelogtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BankConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Final", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Final#DbBankAccountTransactionFinalData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateInitiator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateReceiver")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CreditorIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndToEndReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MandateReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginatorIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("PaymentProcessor")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("TransactionType")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Overridden", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Overridden#DbBankAccountTransactionOverrideData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateInitiator")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateReceiver")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bic")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CreditorIdentifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndToEndReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Iban")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MandateReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginatorIdentifier")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PaymentProcessor")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Purpose")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("TransactionType")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Parsed", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Parsed#DbBankAccountTransactionParsedData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateInitiator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateReceiver")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CreditorIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndToEndReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MandateReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginatorIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("PaymentProcessor")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("TransactionType")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Processed", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Processed#DbBankAccountTransactionProcessedData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateInitiator")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlternateReceiver")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bic")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CreditorIdentifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndToEndReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Iban")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MandateReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginatorIdentifier")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PaymentProcessor")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Purpose")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("TransactionType")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Raw", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Raw#DbBankAccountTransactionRawData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddKey")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Additional")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("ChargeAmount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Code")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndToEndId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("InstituteReference")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsCamt")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsCancelation")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSepa")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MandateId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("NewBalance")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("OriginalAmount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Primanota")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Purpose")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PurposeCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Counterparty", "MoneySpot6.WebApp.Database.DbBankAccountTransaction.Raw#DbBankAccountTransactionRawData.Counterparty#CounterpartyAccount", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("BankCode")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Bic")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Country")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Iban")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name2")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Number")
                                        .HasColumnType("TEXT");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankAccountTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessfulSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbEmailSyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GMailAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSyncTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitoredAddressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GMailAccountId");

                    b.HasIndex("MonitoredAddressId");

                    b.ToTable("EmailSyncStatus");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbGMailIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GMailIntegrations");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbImportedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GMailAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InternalDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitoredAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GMailAccountId");

                    b.HasIndex("MonitoredAddressId");

                    b.ToTable("ImportedEmails");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbInflationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IndexValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InflationData");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbInflationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InflationSettings");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbMonitoredEmailAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonitoredEmailAddresses");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompiledCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSyntaxIssues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeError")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationDaySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalStockValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("SimulationDaySummaries");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("SimulationLogs");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SimulationModels");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationModelRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompiledCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastRunAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SimulationModelId");

                    b.ToTable("SimulationModelRevisions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("SimulationTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastImport5Min")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastImportDaily")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastImportError5Min")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastImportErrorDaily")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockPrices");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbUpdateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpdateLogs");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankConnection", "BankConnection")
                        .WithMany()
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbCategory", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbEmailSyncStatus", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbGMailIntegration", "GMailAccount")
                        .WithMany()
                        .HasForeignKey("GMailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneySpot6.WebApp.Database.DbMonitoredEmailAddress", "MonitoredAddress")
                        .WithMany()
                        .HasForeignKey("MonitoredAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GMailAccount");

                    b.Navigation("MonitoredAddress");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbImportedEmail", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbGMailIntegration", "GMailAccount")
                        .WithMany()
                        .HasForeignKey("GMailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneySpot6.WebApp.Database.DbMonitoredEmailAddress", "MonitoredAddress")
                        .WithMany()
                        .HasForeignKey("MonitoredAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoneySpot6.WebApp.Database.DbExtractedEmailData", "ProcessedData", b1 =>
                        {
                            b1.Property<int>("DbImportedEmailId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Merchant")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrderNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PaymentMethod")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RecipientName")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("Tax")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("TotalAmount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TransactionCode")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("TransactionTimestamp")
                                .HasColumnType("TEXT");

                            b1.HasKey("DbImportedEmailId");

                            b1.ToTable("ImportedEmails");

                            b1.WithOwner()
                                .HasForeignKey("DbImportedEmailId");

                            b1.OwnsMany("MoneySpot6.WebApp.Database.DbExtractedEmailItem", "Items", b2 =>
                                {
                                    b2.Property<int>("DbExtractedEmailDataDbImportedEmailId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("FullName")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ShortName")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal?>("SubTotal")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("DbExtractedEmailDataDbImportedEmailId", "Id");

                                    b2.ToTable("DbExtractedEmailItem");

                                    b2.WithOwner()
                                        .HasForeignKey("DbExtractedEmailDataDbImportedEmailId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("GMailAccount");

                    b.Navigation("MonitoredAddress");

                    b.Navigation("ProcessedData");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationDaySummary", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbSimulationModelRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationLog", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbSimulationModelRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationModelRevision", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbSimulationModel", "SimulationModel")
                        .WithMany()
                        .HasForeignKey("SimulationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationModel");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbSimulationTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbSimulationModelRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockPrice", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbStock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbStockTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbStock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
