// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneySpot6.WebApp.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneySpot6.WebApp.Database.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountSubNumber")
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BankConnectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name2")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankAccountTransactions");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HbciVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Passport")
                        .HasColumnType("bytea");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccount", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankConnection", "BankConnection")
                        .WithMany()
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("MoneySpot6.WebApp.Database.DbBankAccountTransaction", b =>
                {
                    b.HasOne("MoneySpot6.WebApp.Database.DbBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoneySpot6.WebApp.Database.DbBankAccountTransactionRawData", "RawData", b1 =>
                        {
                            b1.Property<int>("DbBankAccountTransactionId")
                                .HasColumnType("integer");

                            b1.Property<string>("AddKey")
                                .HasColumnType("text");

                            b1.Property<string>("Additional")
                                .HasColumnType("text");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint");

                            b1.Property<long>("Balance")
                                .HasColumnType("bigint");

                            b1.Property<long?>("ChargeAmount")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("EndToEndId")
                                .HasColumnType("text");

                            b1.Property<string>("InstituteReference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsCamt")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsSepa")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsStorno")
                                .HasColumnType("boolean");

                            b1.Property<string>("ManadateI")
                                .HasColumnType("text");

                            b1.Property<long?>("OriginalAmount")
                                .HasColumnType("bigint");

                            b1.Property<string>("Primanota")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PurposeCode")
                                .HasColumnType("text");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Usage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DbBankAccountTransactionId");

                            b1.ToTable("BankAccountTransactions");

                            b1.WithOwner()
                                .HasForeignKey("DbBankAccountTransactionId");
                        });

                    b.Navigation("BankAccount");

                    b.Navigation("RawData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
