name: ci

env:
  NAME: "moneyspot"
  HOST_PROD: 192.168.178.200
  HOST_STAGING: 192.168.178.201

on:
  push:

jobs:
  build:
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build --build-arg BUILD_TIME="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg BUILD_COMMIT=${{ github.sha }} -t docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:latest -t docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }} .
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.dvetter.net -u '${{ secrets.DOCKER_USER }}' --password-stdin
      - name: Push to docker registry
        run: |
          docker push docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}
          docker push docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:latest 
          docker push docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }}

  deployment-staging:
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_SSH_KEY  }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no root@${{ env.HOST_STAGING }} "echo Connection successful"
      - name: Updating deployment
        run: |
          export DOCKER_HOST=ssh://root@${{ env.HOST_STAGING }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.dvetter.net -u '${{ secrets.DOCKER_USER }}' --password-stdin
          docker stop ${{ env.NAME }} || true
          docker rm ${{ env.NAME }} || true
          docker pull docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }}
          docker run -d --restart always -p 80:80 --name ${{ env.NAME }} \
            -e ASPNETCORE_ENVIRONMENT="Staging" \
            -e OTEL_EXPORTER_OTLP_ENDPOINT="http://192.168.178.111:4318" \
            -e OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf \
            -e OTEL_SERVICE_NAME="${{ env.NAME }}-app-staging" \
            -e ConnectionStrings__Db="User ID=postgres;Password=${{ secrets.DB_PASSWORD }};Host=192.168.178.105;Port=5432;Database=${{ env.NAME }}-db-staging;ApplicationName=${{ env.NAME }}-staging" \
            docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }}      
          docker image prune -af

  deployment-prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_SSH_KEY  }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no root@${{ env.HOST_PROD }} "echo Connection successful"
      - name: Updating deployment
        run: |
          export DOCKER_HOST=ssh://root@${{ env.HOST_PROD }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.dvetter.net -u '${{ secrets.DOCKER_USER }}' --password-stdin
          docker stop ${{ env.NAME }} || true
          docker rm ${{ env.NAME }} || true
          docker pull docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }}
          docker run -d --restart always -p 80:80 --name ${{ env.NAME }} \
            -e ASPNETCORE_ENVIRONMENT="Production" \
            -e OTEL_EXPORTER_OTLP_ENDPOINT="http://192.168.178.111:4318" \
            -e OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf \
            -e OTEL_SERVICE_NAME="${{ env.NAME }}-app-prod" \
            -e ConnectionStrings__Db="User ID=postgres;Password=${{ secrets.DB_PASSWORD }};Host=192.168.178.105;Port=5432;Database=${{ env.NAME }}-db-prod;ApplicationName=${{ env.NAME }}-prod" \
            docker.dvetter.net/${{ env.NAME }}/${{ env.NAME }}:${{ github.sha }}      
          docker image prune -af