name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: dvetter/moneyspot6:latest , dvetter/moneyspot6:${{ github.sha }}
      - name: Create dep package
        run: |
          mkdir -p build
          TEMPCONTAINER=$(docker create dvetter/moneyspot6:${{ github.sha }})
          docker cp $TEMPCONTAINER:/app ./build
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: App package
          path: build/app


  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: src/deployment/webapp.yaml
      - uses: azure/setup-kubectl@v4
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - uses: Azure/k8s-deploy@v5
        with:
          namespace: 'moneyspot6'
          manifests: src/deployment/webapp.yaml
          images: 'dvetter/moneyspot6:${{ github.sha }}'
          pull-images: false